langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
  app: glitch-craft
    secure: iXpd1qpkDtCIcYNx3wRSGWj7k1iuxfI5lTABJlVADpQVR8EjCGGV01+1TBYOvEFMFtxVQf/r6txgTOpCvlOtpj5K6rAf+NbWtPZYbdQ2y5fO+Tf/IiRnSCMW2itlY7u1kaZZbMRbAQ/XVuri38bYNn/4P7Z2PUUVJMLfRPyi1orsU1Rq4pMG3mSPMk7E5d/6qwW8Lx0PS45luFg7ZL+BSklqjPHnOHk7MrX68Wm8FtAbJ3z5OF/ER61NXHoov7Cga5zWNAktHhhOBpdQQ0OqM2z6iPlaL+8ApTB62wC9SlglL9B5Gy4TEkYOfhVo8ZCFqZnYYLRD7lhBIqaFQT8DxSdKlRfcOzLwraaqU8LycsXRvxgrq8VNy63XdYI6MMzJSWgi/DoxS4Lg6KJ03oVy3llql9GBRSVo+QsWrYCJdCnUN/znnc9SvN5ytrfB0qvRn5xvQRZwnR33B4Bft2nSPZnv+q+qoRijm17V46OlNiXDB6BmR3LXRefT2lRStqlxBHUONNHGfum0l28qMG4Nme7xlrmJi5J8UOUjag1LkN4BckpTT0dZVPrV3AiUOYzwkXgI3uzsEnsliWxJGlENzTipCzC8SfprOdvC6rLkz841YmabR30eZKGZrUXmh/MJBM/q79aS8f5d2LvBxnHZXaJC2pV9iIu2bJ2BZhZUoRE=
  run: "rails db:migrate"
